app:
  mastodon:
    website: ${MASTODON_WEBSITE}
    accountId: ${MASTODON_ACCOUNT_ID}
    clientId: ${MASTODON_CLIENT_KEY}
    clientSecret: ${MASTODON_CLIENT_SECRET}
    consumerKey: ${MASTODON_CONSUMER_KEY}
    consumerSecret: ${MASTODON_CONSUMER_SECRET}
  bluesky:
    accountId: ${BLUESKY_ACCOUNT_ID}
    password: ${BLUESKY_PASSWORD}

springdoc:
  api-docs:
    path: /api-json
  swagger-ui:
    path: /docs